-- TOP

SELECT TOP 10 * FROM Customers	



--ORDER BY
 SELECT TOP 10 * FROM Customers	ORDER BY CustomerID	DESC



 -- EMPLOYEES IN LONDON

 SELECT * FROM Employees where City = 'London'


 -- EMPLOYEES WHO ARE A DOCTOR
 SELECT * FROM Employees WHERE Title = 'Dr.'

 -- PRODUCTS DISCONTINUED
 
SELECT * FROM Products WHERE Discontinued = 1


 -- NUMBER OF CUSTOMERS
 SELECT COUNT(*) AS 'NUMBER OF CUSTOMERS' FROM Customers

 -- NUMBER OF PRODUCTS
  SELECT COUNT(*) AS 'NUMBER OF PRODUCTS' FROM Products
 -- NUMBER OF ORDERS
  SELECT COUNT(*) AS 'NUMBER OF ORDERS' FROM Orders
 
 -- LIST PRODUCT CATEGORIES

 SELECT * FROM Categories

 SELECT COUNT(*) AS 'NUMBER OF DISCUNTINUED' FROM Categories WHERE CategoryID = 1	


