 use TaskDB
 go

DROP DATABASE IF EXISTS TaskDB
GO
  CREATE DATABASE TaskDB



 DROP TABLE IF EXISTS Tasks
 GO
 DROP TABLE IF EXISTS Categories
 GO
 DROP TABLE IF EXISTS Users
 GO


 -- TaskID , DESCRIPTION, CATEGORYID, USERID, DONE(BOOLEAN), DATEDONE(DATE)

 CREATE TABLE Categories(
 CategoryId INT IDENTITY PRIMARY KEY NOT NULL,
 CategoryName VARCHAR (50) NULL

 )

 INSERT INTO Categories VALUES('Bill')
 INSERT INTO Categories VALUES('Katy')
 INSERT INTO Categories VALUES('Nick')
 INSERT INTO Categories VALUES('Mike')


 CREATE TABLE Users(
 UserId INT IDENTITY PRIMARY KEY NOT NULL,
 UserName VARCHAR(50) NULL
 )

 INSERT INTO Users VALUES('Bob'),('Hemat'),('Ben')

 CREATE TABLE Tasks(
 TaskID INT IDENTITY NOT NULL PRIMARY KEY,
 Description VARCHAR(50) NULL,
 Done BIT NULL,
 DateCompleted DATE NULL,
 CategoryID INT NULL,
 UserID INT NULL,
 --FOREIGN KEYS
 FOREIGN KEY (CategoryId) REFERENCES Categories (CategoryId),
 FOREIGN KEY (UserId) REFERENCES Users (UserId)

 )
 GO


 INSERT INTO Tasks VALUES('TEST', 1, '2019/11/24', 1,1)
 INSERT INTO Tasks VALUES('TEST', 0, '2019/11/23', 2,2)
 INSERT INTO Tasks VALUES('TEST', 2, '2019/11/22', 3,3)
 
 SELECT * FROM Categories
 SELECT * FROM Users
 SELECT * FROM Tasks
